### ISSUE TITLE
Finish placing the last four player positions. 

### ISSUE THREAD

**Issue by Scabandari** [Scabandari/casino#2]
Right now I have player positions and hands can be dealt to the 12 o'clock, 6 o'clock, left and right positions. Include the last four positions and rotate the hands so that each looks realistic from an A.I player's perspective.

**Comment by KonradLinkowski** [comment]
You've chosen hours as position and want to insert 8 places around the table. I'll be hard because 12 isn't divisible by 8. I would recommend renaming.
Maybe use some loop [here](https://github.com/Scabandari/casino/blob/master/src/components/Table/Table.jsx#L31).

**Comment by Scabandari** [comment]
> You've chosen hours as position and want to insert 8 places around the table. I'll be hard because 12 isn't divisible by 8. I would recommend renaming.
> Maybe use some loop [here](https://github.com/Scabandari/casino/blob/master/src/components/Table/Table.jsx#L31).

Yes once the placement/location of the hands with respect to the table are set I'd like to dynamically render them with a loop. I'll take your advice on the renaming. I think north, north_east, east, ... would be better. Thanks for the input!!!
